name: test-dependencies
description: Installs test dependencies for monero-oxide (Shekyl fork)

inputs:
  shekyl-version:
    description: "Shekyl daemon version to use for integration tests"
    required: false
    default: latest

runs:
  using: "composite"
  steps:
    - name: Install Build Dependencies
      uses: ./.github/actions/build-dependencies

    - name: Run a Shekyl Regtest Node
      uses: ./.github/actions/monero
      with:
        version: ${{ inputs.shekyl-version }}

    - name: Run a Monero Wallet-RPC
      uses: ./.github/actions/monero-wallet-rpc
