name: test-dependencies
description: Installs test dependencies for shekyl-oxide

inputs:
  shekyl-version:
    description: "Shekyl daemon version to use for integration tests"
    required: false
    default: latest

runs:
  using: "composite"
  steps:
    - name: Install Build Dependencies
      uses: ./.github/actions/build-dependencies

    - name: Run a Shekyl Regtest Node
      uses: ./.github/actions/shekyl
      with:
        version: ${{ inputs.shekyl-version }}

    - name: Run a Shekyl Wallet-RPC
      uses: ./.github/actions/shekyl-wallet-rpc
